---
name: Deployment
on:
  workflow_dispatch:
  
jobs:
  build-production:
    defaults:
      run:
        shell: bash
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current date for release tag
        id: date
        run: echo "TAG_DATE=$(TZ="America/Los_Angeles" date +'%Y-%m-%d')" >> $GITHUB_ENV
        
      - name: Create GitHub release tag
        id: create_release
        uses: release-drafter/release-drafter@v5
        with:
          name: ${{ env.TAG_DATE }} - Deployment ${{ github.run_id }}
          tag: ${{ env.TAG_DATE }}-${{ github.run_id }}
          version: ${{ env.TAG_DATE }}-${{ github.run_id }}
          publish: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
